"""added admin colmn in model_config

Revision ID: 053adb646257
Revises: 90a59b8e24a3
Create Date: 2026-04-07 08:04:00.746489

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '053adb646257'
down_revision: Union[str, Sequence[str], None] = '90a59b8e24a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_model_configs', sa.Column('admin_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'ai_model_configs', 'admin', ['admin_id'], ['admin_id'])
    # op.alter_column('candidates', 'email_from_sender',
    #            existing_type=sa.BOOLEAN(),
    #            nullable=True,
    #            existing_server_default=sa.text('false'))
    # op.drop_constraint(op.f('uq_email_logs_email_id'), 'email_logs', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_email_logs_email_id'), 'email_logs', ['email_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('candidates', 'email_from_sender',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_constraint(None, 'ai_model_configs', type_='foreignkey')
    op.drop_column('ai_model_configs', 'admin_id')
    # ### end Alembic commands ###
