"""created userquery

Revision ID: 0dc07f052f1b
Revises: 7ca2cc30dbb3
Create Date: 2026-04-10 15:03:10.948485

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0dc07f052f1b'
down_revision: Union[str, Sequence[str], None] = '7ca2cc30dbb3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint(op.f('uq_email_logs_email_id'), 'email_logs', type_='unique')
    op.add_column('query_log', sa.Column('user_query', sa.Text(), nullable=False))
    op.add_column('query_log', sa.Column('query_filter', sa.JSON(), nullable=True))
    op.drop_column('query_log', 'filtered_query')
    op.drop_column('query_log', 'query')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_query', sa.Column('query', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('user_query', sa.Column('filtered_query', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('user_query', 'query_filter')
    op.drop_column('user_query', 'user_query')
    op.create_unique_constraint(op.f('uq_email_logs_email_id'), 'email_logs', ['email_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
