"""changes in ai_model_configs

Revision ID: 17b362334785
Revises: 4f6e784741de
Create Date: 2026-06-23 13:07:10.823310

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17b362334785'
down_revision: Union[str, Sequence[str], None] = '4f6e784741de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_model_configs', sa.Column('token_usage', sa.Integer(), nullable=True))
    op.add_column('ai_model_configs', sa.Column('base_url', sa.String(length=255), nullable=True))
    op.add_column('ai_model_configs', sa.Column('prioprity_queue', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ai_model_configs', 'prioprity_queue')
    op.drop_column('ai_model_configs', 'base_url')
    op.drop_column('ai_model_configs', 'token_usage')
    # ### end Alembic commands ###
