"""added fields in  resume models

Revision ID: 3778cc256d84
Revises: 99fe150490dc
Create Date: 2026-03-20 09:39:10.800451

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3778cc256d84'
down_revision: Union[str, Sequence[str], None] = '99fe150490dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_index(op.f('ix_resumes_id'), table_name='resumes')
    # op.drop_table('resumes')
    op.add_column(
        "resumes",
        sa.Column("email_id", sa.Integer(), nullable=True)
    )

    # 2. Add foreign key constraint
    op.create_foreign_key(
        "fk_resumes_email_id",   # constraint name (can be anything)
        "resumes",               # source table
        "emails",                # target table
        ["email_id"],            # local column
        ["id"]                   # remote column
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resumes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('file_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('total_experience', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('skills', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True),
    sa.Column('companies', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True),
    sa.Column('education', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('embedding', sa.LargeBinary(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('resumes_pkey'))
    )
    op.create_index(op.f('ix_resumes_id'), 'resumes', ['id'], unique=False)
    # ### end Alembic commands ###
