"""config model Is_active

Revision ID: 59d63bbae7d6
Revises: 0d29c7393d64
Create Date: 2026-04-15 10:05:36.139474

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59d63bbae7d6'
down_revision: Union[str, Sequence[str], None] = '0d29c7393d64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.alter_column(
        "ai_model_configs",
        "is_active",
        existing_type=sa.Boolean(),
        server_default=sa.text("false"),
        existing_nullable=True,
    )
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
