"""renamed auth_mail to users

Revision ID: 6125d3e8e212
Revises: c671ecb63533
Create Date: 2026-04-13 08:15:46.986861

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6125d3e8e212'
down_revision: Union[str, Sequence[str], None] = 'c671ecb63533'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table("auth_mail", "users")
    op.alter_column('users', 'users_id', new_column_name='user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table("users", "auth_mail")
    

    # ### end Alembic commands ###
