"""modified interview status

Revision ID: 67efe51f1150
Revises: 88f000697c76
Create Date: 2026-05-20 06:35:33.609409

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '67efe51f1150'
down_revision: Union[str, Sequence[str], None] = '88f000697c76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    op.add_column(
        'interview_status',
        sa.Column(
            'interview_status_id',
            postgresql.UUID(as_uuid=True),
            nullable=True
        )
    )

    op.execute("""
        UPDATE interview_status
        SET interview_status_id = gen_random_uuid()
        WHERE interview_status_id IS NULL
    """)

    op.alter_column(
        'interview_status',
        'interview_status_id',
        nullable=False
    )

    op.drop_constraint(
        'interview_status_pkey',
        'interview_status',
        type_='primary'
    )

    op.create_primary_key(
        'interview_status_pkey',
        'interview_status',
        ['interview_status_id']
    )

    op.drop_column('interview_status', 'interview_round_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interview_status', sa.Column('interview_round_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_column('interview_status', 'interview_status_id')
    # ### end Alembic commands ###
