"""Added fields in users

Revision ID: 7ca2cc30dbb3
Revises: e0c93e322ea5
Create Date: 2026-04-10 12:33:47.451007

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ca2cc30dbb3'
down_revision: Union[str, Sequence[str], None] = 'e0c93e322ea5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('phone_number', sa.String(length=20), nullable=True))
    # op.drop_constraint(op.f('uq_email_logs_email_id'), 'email_logs', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_email_logs_email_id'), 'email_logs', ['email_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('users', 'phone_number')
    op.drop_column('users', 'name')
    # ### end Alembic commands ###
