"""add 2 column

Revision ID: 8276ff4c1c94
Revises: 59d63bbae7d6
Create Date: 2026-04-16 06:19:21.977753

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8276ff4c1c94'
down_revision: Union[str, Sequence[str], None] = '59d63bbae7d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_logs', sa.Column('source_mail', sa.String(), nullable=True))
    op.add_column('oauth_credentials', sa.Column('last_processed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('oauth_credentials', 'last_processed_at')
    op.drop_column('email_logs', 'source_mail')
    # ### end Alembic commands ###
