"""changes in schedular

Revision ID: 87649ddf3a40
Revises: 6125d3e8e212
Create Date: 2026-04-13 10:50:00.846865

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '87649ddf3a40'
down_revision: Union[str, Sequence[str], None] = '6125d3e8e212'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('auth_mail')
    op.add_column('extraction_config', sa.Column('schedule_type', sa.String(length=10), nullable=True))
    op.add_column('extraction_config', sa.Column('weekday', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('extraction_config', 'weekday')
    op.drop_column('extraction_config', 'schedule_type')
    op.create_table('auth_mail',
    sa.Column('auth_mail_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('email_address', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('phone_number', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('password', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('connect_with', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('is_blocked', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('extraction_enabled', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('last_extraction_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('auth_mail_id', name=op.f('auth_mail_pkey'))
    )
    # ### end Alembic commands ###
