"""added table for tracking interviews

Revision ID: 88f000697c76
Revises: 72ba7423be23
Create Date: 2026-05-15 13:13:42.898517

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '88f000697c76'
down_revision: Union[str, Sequence[str], None] = '72ba7423be23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('contact_person', sa.String(length=255), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('email_address', sa.String(length=255), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('client_id')
    )
    op.create_table('interview_rounds',
    sa.Column('round_id', sa.UUID(), nullable=False),
    sa.Column('round_name', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('round_id')
    )
    op.create_table('candidate_interviews',
    sa.Column('interview_id', sa.UUID(), nullable=False),
    sa.Column('resume_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('experience', sa.String(length=5), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.client_id'], ),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.resume_id'], ),
    sa.PrimaryKeyConstraint('interview_id')
    )
    op.create_table('interview_status',
    sa.Column('interview_round_id', sa.UUID(), nullable=False),
    sa.Column('interview_id', sa.UUID(), nullable=False),
    sa.Column('round_id', sa.UUID(), nullable=False),
    sa.Column('round_no', sa.String(length=5), nullable=False),
    sa.Column('scheduled_date', sa.DateTime(), nullable=True),
    sa.Column('meeting_link', sa.String(length=255), nullable=False),
    sa.Column('feedback', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['interview_id'], ['candidate_interviews.interview_id'], ),
    sa.ForeignKeyConstraint(['round_id'], ['interview_rounds.round_id'], ),
    sa.PrimaryKeyConstraint('interview_round_id')
    )
    op.drop_table('email_share_logs')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_share_logs',
    sa.Column('email_share_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('to_address', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('cc_address', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('candidate_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('resume_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('create_by', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.candidate_id'], name=op.f('email_share_logs_candidate_id_fkey')),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.resume_id'], name=op.f('email_share_logs_resume_id_fkey1')),
    sa.PrimaryKeyConstraint('email_share_id', name=op.f('email_share_logs_pkey'))
    )
    op.drop_table('interview_status')
    op.drop_table('candidate_interviews')
    op.drop_table('interview_rounds')
    op.drop_table('clients')
    # ### end Alembic commands ###
