"""added exp,role,company table

Revision ID: ae9d22c90cea
Revises: f64b5299158d
Create Date: 2026-03-26 05:29:13.320924

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae9d22c90cea'
down_revision: Union[str, Sequence[str], None] = 'f64b5299158d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('company_location', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('company_id'),
    sa.UniqueConstraint('company_name')
    )
    op.create_table('roles',
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('role_id'),
    sa.UniqueConstraint('role')
    )
    op.create_table('work_experience',
    sa.Column('experience_id', sa.UUID(), nullable=False),
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.candidate_id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['company.company_id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.role_id'], ),
    sa.PrimaryKeyConstraint('experience_id')
    )
    op.add_column('candidate_education', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('candidate_education', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('candidate_education', sa.Column('created_by', sa.String(), nullable=True))
    op.add_column('candidate_education', sa.Column('updated_by', sa.String(), nullable=True))
    op.add_column('candidate_education', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('candidate_skills', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('candidate_skills', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('candidate_skills', sa.Column('created_by', sa.String(), nullable=True))
    op.add_column('candidate_skills', sa.Column('updated_by', sa.String(), nullable=True))
    op.add_column('candidate_skills', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('education', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('education', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('education', sa.Column('created_by', sa.String(), nullable=True))
    op.add_column('education', sa.Column('updated_by', sa.String(), nullable=True))
    op.add_column('education', sa.Column('is_active', sa.Boolean(), nullable=True))
    # op.drop_constraint(op.f('uq_email_logs_email_id'), 'email_logs', type_='unique')
    op.add_column('skills', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('skills', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('skills', sa.Column('created_by', sa.String(), nullable=True))
    op.add_column('skills', sa.Column('updated_by', sa.String(), nullable=True))
    op.add_column('skills', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('skills', 'is_active')
    op.drop_column('skills', 'updated_by')
    op.drop_column('skills', 'created_by')
    op.drop_column('skills', 'updated_at')
    op.drop_column('skills', 'created_at')
    op.create_unique_constraint(op.f('uq_email_logs_email_id'), 'email_logs', ['email_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('education', 'is_active')
    op.drop_column('education', 'updated_by')
    op.drop_column('education', 'created_by')
    op.drop_column('education', 'updated_at')
    op.drop_column('education', 'created_at')
    op.drop_column('candidate_skills', 'is_active')
    op.drop_column('candidate_skills', 'updated_by')
    op.drop_column('candidate_skills', 'created_by')
    op.drop_column('candidate_skills', 'updated_at')
    op.drop_column('candidate_skills', 'created_at')
    op.drop_column('candidate_education', 'is_active')
    op.drop_column('candidate_education', 'updated_by')
    op.drop_column('candidate_education', 'created_by')
    op.drop_column('candidate_education', 'updated_at')
    op.drop_column('candidate_education', 'created_at')
    op.drop_table('work_experience')
    op.drop_table('roles')
    op.drop_table('company')
    # ### end Alembic commands ###
