"""added paasword for admin and users

Revision ID: aeda0174eb0c
Revises: f85d8b4201e7
Create Date: 2026-04-04 06:41:56.091168

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aeda0174eb0c'
down_revision: Union[str, Sequence[str], None] = 'f85d8b4201e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin', sa.Column('password', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('password', sa.String(length=255), nullable=True))
    # op.alter_column('candidates', 'email_from_sender',
    #            existing_type=sa.BOOLEAN(),
    #            nullable=True,
    #            existing_server_default=sa.text('false'))
    # op.drop_constraint(op.f('uq_email_logs_email_id'), 'email_logs', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_email_logs_email_id'), 'email_logs', ['email_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('candidates', 'email_from_sender',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_column('users', 'password')
    op.drop_column('admin', 'password')
    # ### end Alembic commands ###
