"""changes in log_user_query

Revision ID: c671ecb63533
Revises: 0dc07f052f1b
Create Date: 2026-04-13 06:14:19.005072

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c671ecb63533'
down_revision: Union[str, Sequence[str], None] = '0dc07f052f1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table("query_log", "log_user_query")
    op.drop_constraint(
        "query_log_candidate_id_fkey",  # ⚠️ confirm this name in DB
        "log_user_query",
        type_="foreignkey"
    )
    op.drop_column("log_user_query", "candidate_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
            "log_user_query",
            sa.Column("candidate_id", sa.UUID(), nullable=False)
        )

        # 2. Recreate foreign key
    op.create_foreign_key(
        "query_log_candidate_id_fkey",
        "log_user_query",
        "candidates",
        ["candidate_id"],
        ["candidate_id"]
    )

    # 3. Rename table back
    op.rename_table("log_user_query", "query_log")
    # ### end Alembic commands ###
