"""resume pk_id

Revision ID: c78006f1b190
Revises: ae9d22c90cea
Create Date: 2026-03-26 05:37:41.828043

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c78006f1b190'
down_revision: Union[str, Sequence[str], None] = 'ae9d22c90cea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS pgcrypto")

    op.execute("""
        UPDATE resumes
        SET resume_id = gen_random_uuid()
        WHERE resume_id IS NULL
    """)

    op.alter_column("resumes", "resume_id", nullable=False)

    op.create_primary_key("resumes_pkey", "resumes", ["resume_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("resumes_pkey", "resumes", type_="primary")
    # ### end Alembic commands ###
