"""added 2 columns in modelusage

Revision ID: c96238d8f405
Revises: 1f5a40437282
Create Date: 2026-07-01 11:59:29.037545

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c96238d8f405'
down_revision: Union[str, Sequence[str], None] = '1f5a40437282'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_model_usage', sa.Column('minute_requests_received', sa.Integer(), nullable=True))
    op.add_column('ai_model_usage', sa.Column('minute_tokens_used', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ai_model_usage', 'minute_tokens_used')
    op.drop_column('ai_model_usage', 'minute_requests_received')
    # ### end Alembic commands ###
