"""Added share_email_logs table

Revision ID: d84b98443144
Revises: e5f6a7b8c9d0
Create Date: 2026-05-08 14:42:08.839457

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd84b98443144'
down_revision: Union[str, Sequence[str], None] = 'e5f6a7b8c9d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_share_logs', sa.Column('email_share_id', sa.UUID(), nullable=False))
    op.add_column('email_share_logs', sa.Column('to_address', sa.String(length=255), nullable=False))
    op.add_column('email_share_logs', sa.Column('cc_address', sa.String(length=255), nullable=False))
    op.add_column('email_share_logs', sa.Column('candidate_id', sa.UUID(), nullable=False))
    op.add_column('email_share_logs', sa.Column('resume_id', sa.UUID(), nullable=False))
    op.add_column('email_share_logs', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('email_share_logs', sa.Column('create_by', sa.String(length=255), nullable=True))
    op.add_column('email_share_logs', sa.Column('updated_by', sa.String(length=255), nullable=True))
    op.add_column('email_share_logs', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('email_share_logs', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'email_share_logs', 'candidates', ['candidate_id'], ['candidate_id'])
    op.create_foreign_key(None, 'email_share_logs', 'resumes', ['resume_id'], ['resume_id'])
    op.drop_column('email_share_logs', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_share_logs', sa.Column('id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'email_share_logs', type_='foreignkey')
    op.drop_constraint(None, 'email_share_logs', type_='foreignkey')
    op.drop_column('email_share_logs', 'updated_at')
    op.drop_column('email_share_logs', 'created_at')
    op.drop_column('email_share_logs', 'updated_by')
    op.drop_column('email_share_logs', 'create_by')
    op.drop_column('email_share_logs', 'is_active')
    op.drop_column('email_share_logs', 'resume_id')
    op.drop_column('email_share_logs', 'candidate_id')
    op.drop_column('email_share_logs', 'to_address')
    op.drop_column('email_share_logs', 'email_share_id')
    # ### end Alembic commands ###
