"""Added column in resume and oauth

Revision ID: e0c93e322ea5
Revises: 1d02478852e2
Create Date: 2026-04-09 15:51:33.701740

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0c93e322ea5'
down_revision: Union[str, Sequence[str], None] = '1d02478852e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint(op.f('uq_email_logs_email_id'), 'email_logs', type_='unique')
    op.add_column('oauth_credentials', sa.Column('api_domain', sa.String(), nullable=True))
    op.add_column('resumes', sa.Column('candidate_role', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resumes', 'candidate_role')
    op.drop_column('oauth_credentials', 'api_domain')
    op.create_unique_constraint(op.f('uq_email_logs_email_id'), 'email_logs', ['email_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
