"""added skill,candiate_skill,candidate_education table

Revision ID: f64b5299158d
Revises: ee6eabbec140
Create Date: 2026-03-25 16:02:24.247202

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f64b5299158d'
down_revision: Union[str, Sequence[str], None] = 'ee6eabbec140'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('education',
    sa.Column('education_id', sa.UUID(), nullable=False),
    sa.Column('education', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('education_id'),
    sa.UniqueConstraint('education')
    )
    op.create_table('skills',
    sa.Column('skill_id', sa.UUID(), nullable=False),
    sa.Column('skill', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('skill_id'),
    sa.UniqueConstraint('skill')
    )
    op.create_table('candidate_education',
    sa.Column('candidate_education_id', sa.UUID(), nullable=False),
    sa.Column('candidate_id', sa.UUID(), nullable=True),
    sa.Column('institution', sa.String(length=255), nullable=True),
    sa.Column('percentage', sa.Float(), nullable=True),
    sa.Column('year_of_passed', sa.Integer(), nullable=True),
    sa.Column('education_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.candidate_id'], ),
    sa.ForeignKeyConstraint(['education_id'], ['education.education_id'], ),
    sa.PrimaryKeyConstraint('candidate_education_id')
    )
    op.create_table('candidate_skills',
    sa.Column('candidate_skills_id', sa.UUID(), nullable=False),
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('skill_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.candidate_id'], ),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.skill_id'], ),
    sa.PrimaryKeyConstraint('candidate_skills_id')
    )
    # op.drop_constraint(op.f('uq_email_logs_email_id'), 'email_logs', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_email_logs_email_id'), 'email_logs', ['email_id'], postgresql_nulls_not_distinct=False)
    op.drop_table('candidate_skills')
    op.drop_table('candidate_education')
    op.drop_table('skills')
    op.drop_table('education')
    # ### end Alembic commands ###
