"""added auth and model tables

Revision ID: f85d8b4201e7
Revises: a7a9d1b2c3f4
Create Date: 2026-04-04 06:22:54.121414

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f85d8b4201e7'
down_revision: Union[str, Sequence[str], None] = 'a7a9d1b2c3f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('admin_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('email_address', sa.String(length=255), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('admin_id')
    )
    op.create_table('ai_models',
    sa.Column('ai_model_id', sa.UUID(), nullable=False),
    sa.Column('model_name', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('ai_model_id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('email_address', sa.String(length=255), nullable=True),
    sa.Column('connect_with', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('ai_model_version',
    sa.Column('ai_model_version_id', sa.UUID(), nullable=False),
    sa.Column('ai_model_id', sa.UUID(), nullable=True),
    sa.Column('version_name', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['ai_model_id'], ['ai_models.ai_model_id'], ),
    sa.PrimaryKeyConstraint('ai_model_version_id')
    )
    op.create_table('ai_model_configs',
    sa.Column('ai_model_config_id', sa.UUID(), nullable=False),
    sa.Column('ai_model_version_id', sa.UUID(), nullable=True),
    sa.Column('ai_model_id', sa.UUID(), nullable=True),
    sa.Column('apikey', sa.String(length=255), nullable=True),
    sa.Column('version', sa.String(length=255), nullable=True),
    sa.Column('max_tokens', sa.Integer(), nullable=True),
    sa.Column('temparature', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['ai_model_id'], ['ai_models.ai_model_id'], ),
    sa.ForeignKeyConstraint(['ai_model_version_id'], ['ai_model_version.ai_model_version_id'], ),
    sa.PrimaryKeyConstraint('ai_model_config_id')
    )
    # op.alter_column('candidates', 'email_from_sender',
    #            existing_type=sa.BOOLEAN(),
    #            nullable=True,
    #            existing_server_default=sa.text('false'))
    # op.drop_constraint(op.f('uq_email_logs_email_id'), 'email_logs', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_email_logs_email_id'), 'email_logs', ['email_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('candidates', 'email_from_sender',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_table('ai_model_configs')
    op.drop_table('ai_model_version')
    op.drop_table('users')
    op.drop_table('ai_models')
    op.drop_table('admin')
    # ### end Alembic commands ###
